=== lmarent/a-nslp/etc/ipap_xml_message.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT IPAP_MESSAGE (TEMPLATE|DATARECORD)*>
<!ATTLIST IPAP_MESSAGE 
		LAST_TEMPLATE_ID CDATA #REQUIRED
		DOMAIN_ID CDATA #REQUIRED 
		VERSION CDATA #REQUIRED 
		EXPORT_TIME CDATA #REQUIRED
		SEQ_NO CDATA #REQUIRED
		ACK_SEQ_NO CDATA #REQUIRED >
		
<!ELEMENT TEMPLATE (TFIELD*) >
<!ATTLIST TEMPLATE
        ID CDATA #REQUIRED
        TYPE CDATA #REQUIRED
        NUM_FIELDS CDATA #REQUIRED  >        

<!ELEMENT TFIELD (#PCDATA)>
<!ATTLIST TFIELD
        ENO CDATA #REQUIRED
        FTYPE CDATA #REQUIRED
        CODING CDATA #REQUIRED
        LENGTH CDATA #REQUIRED
        XML_NAME CDATA #REQUIRED>
        
<!ELEMENT DATARECORD (FIELD*)>
<!ATTLIST DATARECORD
        TEMPLATE_ID CDATA #REQUIRED>

<!ELEMENT FIELD (#PCDATA)>
<!ATTLIST FIELD
        NAME CDATA #REQUIRED
        ENO CDATA #REQUIRED
        FTYPE CDATA #REQUIRED >

=== lmarent/a-nslp/etc/ipap_message.xml
<!DOCTYPE IPAP_MESSAGE SYSTEM "ipap_xml_message.dtd">
<IPAP_MESSAGE LAST_TEMPLATE_ID="257" DOMAIN_ID="1" VERSION="1" EXPORT_TIME="1444421991" SEQ_NO="5">
	<TEMPLATE ID="256" TYPE="1" NUM_FIELDS="5">
		<TFIELD ENO="0" FTYPE="25" CODING="4" LENGTH="65535" XML_NAME="IdBid">idBid</TFIELD>
		<TFIELD ENO="0" FTYPE="32" CODING="4" LENGTH="65535" XML_NAME="IdRecord">idRecord</TFIELD>
		<TFIELD ENO="0" FTYPE="1" CODING="8" LENGTH="8" XML_NAME="MaxUnitValuation">auctionMaxUnitValuation</TFIELD>
		<TFIELD ENO="0" FTYPE="2" CODING="8" LENGTH="8" XML_NAME="UnitValue">auctionUnitValue</TFIELD>
		<TFIELD ENO="0" FTYPE="33" CODING="5" LENGTH="4" XML_NAME="Quantity">quantity</TFIELD>
	</TEMPLATE>
	<TEMPLATE ID="257" TYPE="4" NUM_FIELDS="5">
		<TFIELD ENO="0" FTYPE="25" CODING="4" LENGTH="65535" XML_NAME="IdBid">idBid</TFIELD>
		<TFIELD ENO="0" FTYPE="24" CODING="4" LENGTH="65535" XML_NAME="IdAuction">idAuction</TFIELD>
		<TFIELD ENO="0" FTYPE="32" CODING="4" LENGTH="65535" XML_NAME="IdRecord">idRecord</TFIELD>
		<TFIELD ENO="0" FTYPE="27" CODING="2" LENGTH="8" XML_NAME="StartSeconds">startSeconds</TFIELD>
		<TFIELD ENO="0" FTYPE="28" CODING="2" LENGTH="8" XML_NAME="EndSeconds">endSeconds</TFIELD>
	</TEMPLATE>
	<DATARECORD TEMPLATE_ID="256">
		<FIELD NAME="MaxUnitValuation" ENO="0" FTYPE="1">0.1500000000</FIELD>
		<FIELD NAME="UnitValue" ENO="0" FTYPE="2">0.1300000000</FIELD>
		<FIELD NAME="IdBid" ENO="0" FTYPE="25">B001</FIELD>
		<FIELD NAME="IdRecord" ENO="0" FTYPE="32">R001</FIELD>
		<FIELD NAME="Quantity" ENO="0" FTYPE="33">0.700000</FIELD>
	</DATARECORD>
	<DATARECORD TEMPLATE_ID="256">
		<FIELD NAME="MaxUnitValuation" ENO="0" FTYPE="1">0.1500000000</FIELD>
		<FIELD NAME="UnitValue" ENO="0" FTYPE="2">0.1300000000</FIELD>
		<FIELD NAME="IdBid" ENO="0" FTYPE="25">B001</FIELD>
		<FIELD NAME="IdRecord" ENO="0" FTYPE="32">R002</FIELD>
		<FIELD NAME="Quantity" ENO="0" FTYPE="33">0.700000</FIELD>
	</DATARECORD>
	<DATARECORD TEMPLATE_ID="256">
		<FIELD NAME="MaxUnitValuation" ENO="0" FTYPE="1">0.1500000000</FIELD>
		<FIELD NAME="UnitValue" ENO="0" FTYPE="2">0.1300000000</FIELD>
		<FIELD NAME="IdBid" ENO="0" FTYPE="25">B001</FIELD>
		<FIELD NAME="IdRecord" ENO="0" FTYPE="32">R003</FIELD>
		<FIELD NAME="Quantity" ENO="0" FTYPE="33">0.700000</FIELD>
	</DATARECORD>
	<DATARECORD TEMPLATE_ID="257">
		<FIELD NAME="IdAuction" ENO="0" FTYPE="24">A001</FIELD>
		<FIELD NAME="IdBid" ENO="0" FTYPE="25">B001</FIELD>
		<FIELD NAME="StartSeconds" ENO="0" FTYPE="27">100</FIELD>
		<FIELD NAME="EndSeconds" ENO="0" FTYPE="28">200</FIELD>
		<FIELD NAME="IdRecord" ENO="0" FTYPE="32">R001</FIELD>
	</DATARECORD>
	<DATARECORD TEMPLATE_ID="257">
		<FIELD NAME="IdAuction" ENO="0" FTYPE="24">A002</FIELD>
		<FIELD NAME="IdBid" ENO="0" FTYPE="25">B001</FIELD>
		<FIELD NAME="StartSeconds" ENO="0" FTYPE="27">100</FIELD>
		<FIELD NAME="EndSeconds" ENO="0" FTYPE="28">200</FIELD>
		<FIELD NAME="IdRecord" ENO="0" FTYPE="32">R003</FIELD>
	</DATARECORD>
</IPAP_MESSAGE>
